spring.application.name=wacdo

spring.datasource.url=jdbc:postgresql://localhost:5432/wacdo

spring.datasource.username=postgres
spring.datasource.password=monPasswordRobust123!

#spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=a-long-time-ago-in-a-galaxy-far-far-away
jwt.expiration=3600000