spring.application.name=wacdo

spring.datasource.url=jdbc:postgresql://localhost:5432/wacdo

spring.datasource.username=postgres
spring.datasource.password=monPasswordRobust123!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true