spring.datasource.url=jdbc:postgresql://localhost:5432/wacdo

spring.datasource.username=postgres
spring.datasource.password=monPasswordRobust123!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# This file should be added to .gitignore but is not for save purpose